name: Hardhat CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install
        working-directory: ./hardhat

      - name: Run Solhint
        run: yarn lint
        working-directory: ./hardhat

      - name: Run Prettier
        run: yarn prettier -c .
        working-directory: ./hardhat

      - name: Run tests
        run: yarn hardhat test
        working-directory: ./hardhat
